version: "3"

# a couple of services for your smarthome, remember to set up your .env file first
services:
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto:1.6"
    restart: unless-stopped
    networks:
      - node-red-net
    volumes:
      - "${DATADIR}/mosquitto/config:/mosquitto/config"
      - "${DATADIR}/mosquitto/data:/mosquitto/data"
      - "${DATADIR}/mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883

  grafana:
    container_name: grafana
    image: "grafana/grafana:latest"
    restart: unless-stopped
    user: "$PUID:$PGID"
    networks:
      - node-red-net
    volumes:
      - "${DATADIR}/grafana/data:/var/lib/grafana"
    ports:
      - 3000:3000
    user: "1014"
    # uncomment this if you wanta to allow anonymus acces to Grafana for embedding (e.g. in Home Assistant dashboards)
    #environment:
    #  - GF_AUTH_DISABLE_LOGIN_FORM=true
    #  - GF_AUTH_ANONYMOUS_ENABLED=true
    #  - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    #  - GF_SECURITY_ALLOW_EMBEDDING=true

  influxdb:
    container_name: influxdb
    image: "influxdb:1.8"
    restart: unless-stopped
    volumes:
      - "${DATADIR}/influxdb/data:/var/lib/influxdb"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    networks:
      - node-red-net
    ports:
      - 127.0.0.1:8086:8086

  tasmoadmin:
    container_name: tasmoadmin
    image: "raymondmm/tasmoadmin"
    restart: unless-stopped
    volumes:
      - "${DATADIR}/tasmoadmin:/data"
    networks:
      - node-red-net
    ports:
      - 3080:80
      
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - ZA=Africa/Johannesburg
    networks:
      - node-red-net
    ports:
      - "1880:1880"
    volumes:
      - "${DATADIR}/node-red-data:/data"

volumes:
  node-red-data:

networks:
  node-red-net:
